### PR TITLE
ADD SUPPORT FOR MUSICS

### PR DESCRIPTION
**Pull request by MaxxCoderZ**
`MUSIC.PY` add will be better good for this repo ;  also add `sample config.py` because heroku suspends now days

### CODE REVIEW

**Comment by xditya** [comment]
but where ?

**Comment by MaxxCoderZ** [comment]
> but where ?

Create a new files

**Comment by xditya** [comment]
> > but where ?
> 
> contact me message @maxxcoderzTG on telegram

Seriously bruh?

**Comment by MaxxCoderZ** [comment]
> > > but where ?
> > 
> > 
> > contact me message @maxxcoderzTG on telegram
> 
> Seriously bruh?

Sorry bro mistakely ; add new files in the repp and add features for music and connect it with your caommands and repo

**Pull request closed without merging**
